version: "3.9"

services:
  laravelapp:
    container_name: laravelapp
    image: messi/laravelapp:1.0.4
    build: 
      context: .
      dockerfile: php.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    